FROM node:20-alpine

WORKDIR /app

# Копируем package файлы
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем исходный код
COPY . .

# Открываем порт
EXPOSE 5175

# Запускаем dev сервер
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5175"]
